import { GoogleGenerativeAI } from "@google/generative-ai";
import type { FloorPlanData } from "./floorplan.types";

const GEMINI_API_KEY = import.meta.env.VITE_GEMINI_API_KEY;
if (!GEMINI_API_KEY) {
  console.warn("VITE_GEMINI_API_KEY not set. Blender script generation will fail.");
}

const genAI = new GoogleGenerativeAI(GEMINI_API_KEY || "");

const BLENDER_GENERATION_PROMPT = `You are an expert Blender Python (bpy) developer.

Here is a floor plan JSON:
<INSERT_JSON_HERE>

Generate a complete Blender Python script that does:

1. Clear the scene:
   bpy.ops.object.select_all(action='SELECT')
   bpy.ops.object.delete()

2. For each room in JSON:
   - bpy.ops.mesh.primitive_cube_add()
   - Set dimensions: x = room.width * 0.3048, y = room.height * 0.3048, z = 2.8
   - Set location: x = (room.x + room.width/2) * 0.3048, y = (room.y + room.height/2) * 0.3048, z = 1.4
   - Create a material named after room.name
   - Assign color by room type (same as: living_room=#E8D5B7, bedroom=#B7C9E8, kitchen=#E8E8B7, bathroom=#B7E8E8, hallway=#D5D5D5, balcony=#C8E8B7, dining=#E8C8B7, office=#C8B7E8, other=#E0E0E0)
   - Name the object room.name

3. For each window in each room:
   - Add a thin cube on the correct wall
   - Apply glass material: transmission=1, IOR=1.45, roughness=0

4. Add Sun lamp:
   - Location (10, 10, 20), energy = 3, name = "DreamLand_Sun"

5. Add Camera:
   - Location (15, -15, 12)
   - Point at origin (0, 0, 0)
   - Name = "DreamLand_Camera"

6. Ground plane:
   - 50x50 flat plane at z=0
   - Gray diffuse material #AAAAAA

7. Render settings:
   - engine = CYCLES
   - resolution_x = 1920, resolution_y = 1080

8. Add this comment at top of script:
# ================================
# Generated by DreamLand AI
# Total Area: <totalArea> sq ft
# Rooms: <count>
# Instructions: Open Blender > Scripting tab > Paste > Run Script
# ================================

Return ONLY the raw Python script. No markdown. No explanation. No backticks.`;

export async function generateBlenderScript(
  floorPlanData: FloorPlanData
): Promise<string> {
  try {
    if (!GEMINI_API_KEY) {
      throw new Error("VITE_GEMINI_API_KEY environment variable not set");
    }

    const jsonString = JSON.stringify(floorPlanData);
    const prompt = BLENDER_GENERATION_PROMPT.replace(
      "<INSERT_JSON_HERE>",
      jsonString
    );

    // Call Gemini to generate script
    const model = genAI.getGenerativeModel({ model: "gemini-2.5-flash" });
    const response = await model.generateContent(prompt);

    // Extract response text
    const responseText = response.response.text();

    // Strip backticks and markdown
    let cleanedScript = responseText
      .replace(/```python\n?/g, "")
      .replace(/```\n?/g, "")
      .trim();

    return cleanedScript;
  } catch (error) {
    throw new Error(
      `Failed to generate Blender script: ${error instanceof Error ? error.message : String(error)}`
    );
  }
}

export function downloadBlenderScript(
  script: string,
  filename: string
): void {
  try {
    // Create blob
    const blob = new Blob([script], { type: "text/plain" });

    // Create object URL
    const url = URL.createObjectURL(blob);

    // Create anchor element
    const link = document.createElement("a");
    link.href = url;
    link.download = filename;

    // Click programmatically
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);

    // Revoke object URL
    URL.revokeObjectURL(url);
  } catch (error) {
    throw new Error(
      `Failed to download Blender script: ${error instanceof Error ? error.message : String(error)}`
    );
  }
}
